### ISSUE TITLE
Labb 3: box-two dyker upp 2 gånger

### ISSUE THREAD

**Issue by perjespersson** [mah-webb/mah-webb.github.io#2]
.box-two dyker upp 2 gånger istället för att första ska vara .box-one :-)
(https://cloud.githubusercontent.com/assets/15002990/10320036/9bdad102-6c71-11e5-9ffe-e9ba7a2337a3.png)

**Comment by trumtomte** [comment]
Fixat! (nästa gång kan du ju skicka lösningen direkt via GitHub så kan vi bara accepta den :+1: )
